### ISSUE TITLE
Use lowercase namespace

### ISSUE THREAD

**Issue by northkill** [skyclad0x7b7/Mini-Mahjong#7]
# Contribution guide proposal

What about using lowercase namespace?
i.e. Instead of using
```
namespace Mini { ... }
```
let's use
```
namespace mini { ... }
```

# Why
For fun of course.
Also, IMO it's more aesthetic and seems more constant using with other libraries like std or boost.
```
// std::vector< Mini::MyClass > hello;
std::vector< mini::my_class > hello;
boost::nuke_this< mini::server > nuke_server;
```

**Comment by skyclad0x7b7** [comment]
I haven't decided naming convention yet, so it might be considered for next convention.
But personally, I just want to use camelCase and PascalCase cuz I like and feel comfortable with these.

Let's discuss about that after this project getting bigger and being more stable.
Thank you for your suggestion.

**Comment by northkill** [comment]
Further documentation will be needed though
